// Variant 2 "White" — single source of the demo catalog, shared by the shop
// grid and the PDP (so a card click opens that product, not a hardcoded one).

export type WhiteCat = 'dresses' | 'outerwear' | 'knitwear' | 'tailoring' | 'skirts';

export type WhiteColor = {key: string; hex: string; en: string; ru: string; image?: string; gallery?: string[]};

export type WhiteProduct = {
  key: number;
  en: string;
  ru: string;
  cat: WhiteCat;
  price: number;
  sale?: number;
  descEn: string;
  descRu: string;
  compositionEn: string;
  compositionRu: string;
  careEn: string;
  careRu: string;
  colors: WhiteColor[];
  // The product's own presentable photo (real WB garment restyled onto the White
  // studio). Same-origin under images/white/products, so CSP img-src 'self' covers it.
  image: string;
  // Optional extra views OF THE SAME product for the PDP gallery. When absent the
  // PDP shows the single `image` — never other products' shots dressed up as views.
  gallery?: string[];
  // The product's Wildberries article — powers the "buy on Wildberries" links.
  nm: number;
};

const IVORY: WhiteColor = {key: 'ivory', hex: '#ece6da', en: 'Ivory', ru: 'Слоновая кость'};
const BLACK: WhiteColor = {key: 'black', hex: '#2b2722', en: 'Black', ru: 'Чёрный'};
const BORDEAUX: WhiteColor = {key: 'bordeaux', hex: '#6e2a2a', en: 'Bordeaux', ru: 'Бордовый'};
const CAMEL: WhiteColor = {key: 'camel', hex: '#b89a6e', en: 'Camel', ru: 'Кэмел'};
const CHARCOAL: WhiteColor = {key: 'charcoal', hex: '#3a3632', en: 'Charcoal', ru: 'Угольный'};
const GREY: WhiteColor = {key: 'grey', hex: '#9a958d', en: 'Grey', ru: 'Серый'};
const SAND: WhiteColor = {key: 'sand', hex: '#d8cdbd', en: 'Sand', ru: 'Песочный'};
const OAT: WhiteColor = {key: 'oat', hex: '#ddd2bf', en: 'Oat', ru: 'Овсяный'};
const NAVY: WhiteColor = {key: 'navy', hex: '#2c3340', en: 'Navy', ru: 'Тёмно-синий'};
const CHAMPAGNE: WhiteColor = {key: 'champagne', hex: '#e3d4bd', en: 'Champagne', ru: 'Шампань'};
const STONE: WhiteColor = {key: 'stone', hex: '#b5ad9f', en: 'Stone', ru: 'Камень'};
const BROWN: WhiteColor = {key: 'brown', hex: '#5c4433', en: 'Brown', ru: 'Коричневый'};
const ROSE: WhiteColor = {key: 'rose', hex: '#d9aca4', en: 'Rose', ru: 'Розовый'};
const GREEN: WhiteColor = {key: 'green', hex: '#6b6f4e', en: 'Olive', ru: 'Оливковый'};
const SKYBLUE: WhiteColor = {key: 'skyblue', hex: '#a9c3d6', en: 'Sky blue', ru: 'Голубой'};
const RED: WhiteColor = {key: 'red', hex: '#a02a24', en: 'Red', ru: 'Красный'};
const YELLOW: WhiteColor = {key: 'yellow', hex: '#e8d07a', en: 'Lemon', ru: 'Лимонный'};
const ORANGE: WhiteColor = {key: 'orange', hex: '#d16a3c', en: 'Terracotta', ru: 'Терракотовый'};

// Real REINASLEO catalogue (WB seller 609562). Names, prices and colours are the
// actual products; each `image` is that real garment restyled onto a clean
// warm-white studio for the White editorial look (real WB photo → reference
// generation). Same-origin JPEGs under images/white/products, CSP img-src 'self'.
export const WHITE_PRODUCTS: WhiteProduct[] = [
  {key: 1, en: 'Linen Maxi Suit', ru: 'Льняной костюм с юбкой макси', cat: 'tailoring', price: 4269, descEn: 'A sleeveless linen vest and a floor-skimming maxi skirt, cut for summer ease. Natural buttons, a defined waist, unlined.', descRu: 'Льняной жилет без рукавов и юбка макси в пол — летняя лёгкость. Натуральные пуговицы, подчёркнутая талия, без подклада.', compositionEn: '100% linen', compositionRu: '100% лён', careEn: 'Machine wash cold, gentle', careRu: 'Деликатная стирка в холодной воде', colors: [IVORY, {...BLACK, image: '/images/white/products/p-1008989269-black.jpg', gallery: ['/images/white/products/p-1008989269-black-b.jpg', '/images/white/products/p-1008989269-black-d.jpg', '/images/white/products/p-1008989269-black-s.jpg', '/images/white/products/p-1008989269-black-m.jpg']}, {...SKYBLUE, image: '/images/white/products/p-1008989269-blue.jpg', gallery: ['/images/white/products/p-1008989269-blue-b.jpg', '/images/white/products/p-1008989269-blue-d.jpg', '/images/white/products/p-1008989269-blue-s.jpg', '/images/white/products/p-1008989269-blue-m.jpg']}, {...YELLOW, image: '/images/white/products/p-1008989269-yellow.jpg', gallery: ['/images/white/products/p-1008989269-yellow-b.jpg', '/images/white/products/p-1008989269-yellow-d.jpg', '/images/white/products/p-1008989269-yellow-s.jpg', '/images/white/products/p-1008989269-yellow-m.jpg']}, {...GREEN, image: '/images/white/products/p-1008989269-green.jpg', gallery: ['/images/white/products/p-1008989269-green-b.jpg', '/images/white/products/p-1008989269-green-d.jpg', '/images/white/products/p-1008989269-green-s.jpg', '/images/white/products/p-1008989269-green-m.jpg']}, {...ORANGE, image: '/images/white/products/p-1008989269-orange.jpg', gallery: ['/images/white/products/p-1008989269-orange-b.jpg', '/images/white/products/p-1008989269-orange-d.jpg', '/images/white/products/p-1008989269-orange-s.jpg', '/images/white/products/p-1008989269-orange-m.jpg']}, {...ROSE, image: '/images/white/products/p-1008989269-rose.jpg', gallery: ['/images/white/products/p-1008989269-rose-b.jpg', '/images/white/products/p-1008989269-rose-d.jpg', '/images/white/products/p-1008989269-rose-s.jpg', '/images/white/products/p-1008989269-rose-m.jpg']}, {...BROWN, image: '/images/white/products/p-1008989269-brown.jpg', gallery: ['/images/white/products/p-1008989269-brown-b.jpg', '/images/white/products/p-1008989269-brown-d.jpg', '/images/white/products/p-1008989269-brown-s.jpg', '/images/white/products/p-1008989269-brown-m.jpg']}], image: '/images/white/products/p-1008989269.jpg', nm: 1008989269, gallery: ['/images/white/products/p-1008989269-3.jpg', '/images/white/products/p-1008989269-4.jpg', '/images/white/products/p-1008989269-5.jpg', '/images/white/products/p-1008989269-6.jpg', '/images/white/products/p-1008989269-7.jpg']},
  {key: 2, en: 'Fitted Blazer Coat', ru: 'Пальто-пиджак приталенное', cat: 'outerwear', price: 34900, descEn: 'A demi-season coat cut like a blazer — clean collarless shoulders and a sculpted, buttoned waist. Fully lined.', descRu: 'Демисезонное пальто с кроем пиджака — чистые плечи без воротника и скульптурная талия на пуговицах. На подкладе.', compositionEn: 'Wool blend', compositionRu: 'Шерстяная смесь', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [SAND, {...CHARCOAL, image: '/images/white/products/p-795522033-charcoal.jpg', gallery: ['/images/white/products/p-795522033-charcoal-b.jpg', '/images/white/products/p-795522033-charcoal-d.jpg', '/images/white/products/p-795522033-charcoal-s.jpg', '/images/white/products/p-795522033-charcoal-m.jpg']}], image: '/images/white/products/p-795522033.jpg', nm: 795522033, gallery: ['/images/white/products/p-795522033-2.jpg', '/images/white/products/p-795522033-3.jpg', '/images/white/products/p-795522033-4.jpg', '/images/white/products/p-795522033-5.jpg', '/images/white/products/p-795522033-6.jpg']},
  {key: 3, en: 'Peplum Suit Vest', ru: 'Жилет костюмный с баской', cat: 'tailoring', price: 4466, descEn: 'A classic tailored vest with a peplum flare and a buttoned front. Nipped at the waist, sharp over anything.', descRu: 'Классический костюмный жилет с баской и застёжкой на пуговицы. Приталенный, острый поверх чего угодно.', compositionEn: 'Cotton blend', compositionRu: 'Хлопковая смесь', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [{...BROWN}, {...BLACK, image: '/images/white/products/p-962827637-black.jpg', gallery: ['/images/white/products/p-962827637-black-b.jpg', '/images/white/products/p-962827637-black-d.jpg', '/images/white/products/p-962827637-black-s.jpg', '/images/white/products/p-962827637-black-m.jpg']}], image: '/images/white/products/p-962827637.jpg', nm: 962827637, gallery: ['/images/white/products/p-962827637-3.jpg', '/images/white/products/p-962827637-4.jpg', '/images/white/products/p-962827637-5.jpg', '/images/white/products/p-962827637-6.jpg', '/images/white/products/p-962827637-7.jpg']},
  {key: 4, en: 'Bow Sweatshirt', ru: 'Свитшот с бантиками', cat: 'knitwear', price: 8000, descEn: 'An oversized cotton sweatshirt softened with bow details. Dropped shoulders, ribbed trims, quiet comfort.', descRu: 'Оверсайз-свитшот из хлопка, смягчённый бантиками. Приспущенное плечо, рубчатые края, тихий комфорт.', compositionEn: 'Cotton blend', compositionRu: 'Хлопковая смесь', careEn: 'Machine wash cold', careRu: 'Машинная стирка в холодной воде', colors: [GREY, {...BLACK, image: '/images/white/products/p-442577291-black.jpg', gallery: ['/images/white/products/p-442577291-black-b.jpg', '/images/white/products/p-442577291-black-d.jpg', '/images/white/products/p-442577291-black-s.jpg', '/images/white/products/p-442577291-black-m.jpg']}], image: '/images/white/products/p-442577291.jpg', nm: 442577291, gallery: ['/images/white/products/p-442577291-2.jpg', '/images/white/products/p-442577291-3.jpg', '/images/white/products/p-442577291-4.jpg', '/images/white/products/p-442577291-b.jpg']},
  // Temporarily off the shelf — its own photography hasn't arrived yet (the
  // stored shot shows a different garment). Uncomment when the photos land.
  // {key: 5, en: 'Lace Pencil Skirt', ru: 'Юбка-карандаш с кружевом', cat: 'skirts', price: 30150, descEn: 'A high-waisted pencil skirt finished with fine lace. Tailored through the hip, midi length, quietly formal.', descRu: 'Юбка-карандаш с высокой посадкой и тонким кружевом. Точный крой по бедру, длина миди, сдержанная торжественность.', compositionEn: 'Wool blend with lace', compositionRu: 'Шерстяная смесь с кружевом', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [IVORY, BLACK], image: '/images/white/products/p-1217805724.jpg', nm: 1217805724},
  {key: 6, en: 'Peplum Evening Corset', ru: 'Корсет вечерний с баской', cat: 'dresses', price: 2932, descEn: 'A structured evening corset with a peplum hem. A boned bodice and a defined waist, made to be dressed up.', descRu: 'Структурный вечерний корсет с баской. Лиф на косточках и чёткая талия — создан для выхода.', compositionEn: 'Cotton blend', compositionRu: 'Хлопковая смесь', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [BLACK, {...SAND, image: '/images/white/products/p-675104410-beige.jpg', gallery: ['/images/white/products/p-675104410-beige-b.jpg', '/images/white/products/p-675104410-beige-d.jpg', '/images/white/products/p-675104410-beige-s.jpg', '/images/white/products/p-675104410-beige-m.jpg']}, {...BROWN, image: '/images/white/products/p-675104410-brown.jpg', gallery: ['/images/white/products/p-675104410-brown-b.jpg', '/images/white/products/p-675104410-brown-d.jpg', '/images/white/products/p-675104410-brown-s.jpg', '/images/white/products/p-675104410-brown-m.jpg']}], image: '/images/white/products/p-675104410.jpg', nm: 675104410, gallery: ['/images/white/products/p-675104410-3.jpg', '/images/white/products/p-675104410-4.jpg', '/images/white/products/p-675104410-b.jpg', '/images/white/products/p-675104410-d.jpg']},
  {key: 7, en: 'Draped Harem Trousers', ru: 'Брюки алладины', cat: 'tailoring', price: 2927, descEn: 'Softly draped harem trousers with a relaxed fall and a clean waist. Easy tailoring for every day.', descRu: 'Мягко драпированные брюки алладины со свободным силуэтом и чистой талией. Лёгкий тайлоринг на каждый день.', compositionEn: 'Viscose blend', compositionRu: 'Вискозная смесь', careEn: 'Machine wash cold', careRu: 'Машинная стирка в холодной воде', colors: [SAND, {...BLACK, image: '/images/white/products/p-962783109-black.jpg', gallery: ['/images/white/products/p-962783109-black-b.jpg', '/images/white/products/p-962783109-black-d.jpg', '/images/white/products/p-962783109-black-s.jpg', '/images/white/products/p-962783109-black-m.jpg']}, {...BROWN, image: '/images/white/products/p-962783109-brown.jpg', gallery: ['/images/white/products/p-962783109-brown-b.jpg', '/images/white/products/p-962783109-brown-d.jpg', '/images/white/products/p-962783109-brown-s.jpg', '/images/white/products/p-962783109-brown-m.jpg']}, {...GREEN, image: '/images/white/products/p-962783109-green.jpg', gallery: ['/images/white/products/p-962783109-green-b.jpg', '/images/white/products/p-962783109-green-d.jpg', '/images/white/products/p-962783109-green-m.jpg', '/images/white/products/p-962783109-green-s.jpg']}], image: '/images/white/products/p-962783109.jpg', nm: 962783109, gallery: ['/images/white/products/p-962783109-3.jpg', '/images/white/products/p-962783109-4.jpg', '/images/white/products/p-962783109-b.jpg', '/images/white/products/p-962783109-d.jpg']},
  {key: 8, en: 'Satin Balloon Skirt', ru: 'Юбка баллон атласная', cat: 'skirts', price: 2565, descEn: 'A satin balloon mini with built-in shorts and a rounded volume. Matte sheen, quiet movement.', descRu: 'Атласная юбка-баллон мини с шортами и округлым объёмом. Матовый блеск, тихое движение.', compositionEn: 'Satin', compositionRu: 'Атлас', careEn: 'Machine wash cold', careRu: 'Машинная стирка в холодной воде', colors: [IVORY, {...BLACK, image: '/images/white/products/p-371980450-black.jpg', gallery: ['/images/white/products/p-371980450-black-b.jpg', '/images/white/products/p-371980450-black-d.jpg', '/images/white/products/p-371980450-black-s.jpg', '/images/white/products/p-371980450-black-m.jpg']}, {...RED, image: '/images/white/products/p-371980450-red.jpg', gallery: ['/images/white/products/p-371980450-red-b.jpg', '/images/white/products/p-371980450-red-d.jpg', '/images/white/products/p-371980450-red-s.jpg', '/images/white/products/p-371980450-red-m.jpg']}], image: '/images/white/products/p-371980450.jpg', nm: 371980450, gallery: ['/images/white/products/p-371980450-2.jpg', '/images/white/products/p-371980450-d.jpg', '/images/white/products/p-371980450-b.jpg', '/images/white/products/p-371980450-s.jpg']},
  {key: 9, en: 'Lace Oversized Shirt', ru: 'Рубашка оверсайз с кружевом', cat: 'dresses', price: 8326, descEn: 'An oversized shirt with a dramatic gathered sleeve — drawn at the wrist with a drawstring tie, a narrow lace edging showing at the cuff. Relaxed shoulders, a curved shirttail hem.', descRu: 'Оверсайз-рубашка с объёмным рукавом — кулиска с завязками у запястья, узкое кружево по краю манжеты. Свободные плечи, скруглённый низ.', compositionEn: 'Cotton with lace trim', compositionRu: 'Хлопок с кружевной отделкой', careEn: 'Hand wash cold', careRu: 'Ручная стирка в холодной воде', colors: [{...BLACK, en: 'Black pinstripe', ru: 'Чёрный в полоску'}, {...SAND, en: 'Vanilla polka dot', ru: 'Ваниль в горошек', image: '/images/white/products/p-1113526969-sand.jpg', gallery: ['/images/white/products/p-1113526969-sand-b.jpg', '/images/white/products/p-1113526969-sand-d.jpg', '/images/white/products/p-1113526969-sand-s.jpg', '/images/white/products/p-1113526969-sand-m.jpg']}, {...GREY, en: 'Grey polka dot', ru: 'Серый в горошек', image: '/images/white/products/p-1113526969-grey.jpg', gallery: ['/images/white/products/p-1113526969-grey-b.jpg', '/images/white/products/p-1113526969-grey-d.jpg', '/images/white/products/p-1113526969-grey-s.jpg', '/images/white/products/p-1113526969-grey-m.jpg']}, {...ROSE, en: 'Rose check', ru: 'Розовая клетка', image: '/images/white/products/p-1113526969-rose.jpg', gallery: ['/images/white/products/p-1113526969-rose-b.jpg', '/images/white/products/p-1113526969-rose-d.jpg', '/images/white/products/p-1113526969-rose-s.jpg', '/images/white/products/p-1113526969-rose-m.jpg']}], image: '/images/white/products/p-1113526969.jpg', nm: 1113526969, gallery: ['/images/white/products/p-1113526969-3.jpg', '/images/white/products/p-1113526969-4.jpg', '/images/white/products/p-1113526969-b.jpg', '/images/white/products/p-1113526969-d.jpg']},
  {key: 10, en: 'Suede Skort', ru: 'Юбка-шорты замшевая', cat: 'skirts', price: 2922, descEn: 'A suede mini skort finished with a scalloped lace hem — the ease of shorts under the line of a skirt. Soft hand, elasticated waist.', descRu: 'Замшевая юбка-шорты с кружевной отделкой по низу — лёгкость шорт под линией юбки. Мягкая фактура, эластичный пояс.', compositionEn: 'Faux suede with lace trim', compositionRu: 'Искусственная замша с кружевом', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [IVORY, {...BROWN, image: '/images/white/products/p-1143078000-brown.jpg', gallery: ['/images/white/products/p-1143078000-brown-b.jpg', '/images/white/products/p-1143078000-brown-d.jpg', '/images/white/products/p-1143078000-brown-s.jpg', '/images/white/products/p-1143078000-brown-m.jpg']}, {...BLACK, image: '/images/white/products/p-1143078000-black.jpg', gallery: ['/images/white/products/p-1143078000-black-b.jpg', '/images/white/products/p-1143078000-black-d.jpg', '/images/white/products/p-1143078000-black-s.jpg', '/images/white/products/p-1143078000-black-m.jpg']}, {...GREEN, image: '/images/white/products/p-1143078000-green.jpg', gallery: ['/images/white/products/p-1143078000-green-b.jpg', '/images/white/products/p-1143078000-green-d.jpg', '/images/white/products/p-1143078000-green-s.jpg', '/images/white/products/p-1143078000-green-m.jpg']}, {...GREY, image: '/images/white/products/p-1143078000-grey.jpg', gallery: ['/images/white/products/p-1143078000-grey-b.jpg', '/images/white/products/p-1143078000-grey-d.jpg', '/images/white/products/p-1143078000-grey-s.jpg', '/images/white/products/p-1143078000-grey-m.jpg']}], image: '/images/white/products/p-1143078000.jpg', nm: 1143078000, gallery: ['/images/white/products/p-1143078000-b.jpg', '/images/white/products/p-1143078000-d.jpg', '/images/white/products/p-1143078000-s.jpg', '/images/white/products/p-1143078000-m.jpg']},
  {key: 11, en: 'Long Belted Coat', ru: 'Пальто оверсайз с поясом', cat: 'outerwear', price: 34900, descEn: 'A long oversized demi-season coat with a self-tie belt. Dropped shoulders, a deep collar, floor-skimming.', descRu: 'Длинное оверсайз-пальто демисезона с поясом. Приспущенное плечо, глубокий воротник, длина в пол.', compositionEn: 'Wool blend', compositionRu: 'Шерстяная смесь', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [BLACK, {...CAMEL, image: '/images/white/products/p-100797221-camel.jpg', gallery: ['/images/white/products/p-100797221-camel-b.jpg', '/images/white/products/p-100797221-camel-d.jpg', '/images/white/products/p-100797221-camel-s.jpg', '/images/white/products/p-100797221-camel-m.jpg']}, {...BROWN, image: '/images/white/products/p-100797221-brown.jpg', gallery: ['/images/white/products/p-100797221-brown-b.jpg', '/images/white/products/p-100797221-brown-d.jpg', '/images/white/products/p-100797221-brown-s.jpg', '/images/white/products/p-100797221-brown-m.jpg']}], image: '/images/white/products/p-100797221.jpg', nm: 100797221, gallery: ['/images/white/products/p-100797221-2.jpg', '/images/white/products/p-100797221-3.jpg', '/images/white/products/p-100797221-b.jpg', '/images/white/products/p-100797221-d.jpg']},
  {key: 12, en: 'Ribbed Slit Dress', ru: 'Платье лапша с разрезом', cat: 'dresses', price: 632, descEn: 'A long ribbed knit dress that skims the body, opened by a single side slit. Second-skin soft.', descRu: 'Длинное платье в рубчик, что скользит по фигуре, с одним боковым разрезом. Мягкое как вторая кожа.', compositionEn: 'Ribbed viscose', compositionRu: 'Вискоза в рубчик', careEn: 'Hand wash cold', careRu: 'Ручная стирка в холодной воде', colors: [OAT, {...GREY, image: '/images/white/products/p-192510012-grey.jpg', gallery: ['/images/white/products/p-192510012-grey-b.jpg', '/images/white/products/p-192510012-grey-d.jpg', '/images/white/products/p-192510012-grey-s.jpg', '/images/white/products/p-192510012-grey-m.jpg']}], image: '/images/white/products/p-192510012.jpg', nm: 192510012, gallery: ['/images/white/products/p-192510012-2.jpg', '/images/white/products/p-192510012-3.jpg', '/images/white/products/p-192510012-4.jpg', '/images/white/products/p-192510012-5.jpg', '/images/white/products/p-192510012-6.jpg', '/images/white/products/p-192510012-7.jpg']},
  {key: 13, en: 'Striped Belted Coat', ru: 'Пальто в полоску с поясом', cat: 'outerwear', price: 34900, descEn: 'A long oversized coat in a fine tonal stripe, closed with a belt. Considered ease over anything.', descRu: 'Длинное оверсайз-пальто в тонкую тональную полоску, на поясе. Продуманная лёгкость поверх чего угодно.', compositionEn: 'Wool blend', compositionRu: 'Шерстяная смесь', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [SAND, {...CHARCOAL, image: '/images/white/products/p-814720607-charcoal.jpg', gallery: ['/images/white/products/p-814720607-charcoal-b.jpg', '/images/white/products/p-814720607-charcoal-d.jpg', '/images/white/products/p-814720607-charcoal-s.jpg', '/images/white/products/p-814720607-charcoal-m.jpg']}], image: '/images/white/products/p-814720607.jpg', nm: 814720607, gallery: ['/images/white/products/p-814720607-2.jpg', '/images/white/products/p-814720607-4.jpg', '/images/white/products/p-814720607-b.jpg', '/images/white/products/p-814720607-d.jpg']},
  {key: 14, en: 'Spring Kimono Coat', ru: 'Пальто кимоно весеннее', cat: 'outerwear', price: 34900, descEn: 'A short kimono-cut coat for spring — wide sleeves, a wrap front, no fuss. Light layering.', descRu: 'Короткое пальто кроя кимоно для весны — широкий рукав, запа́х, без суеты. Лёгкий слой.', compositionEn: 'Wool blend', compositionRu: 'Шерстяная смесь', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [SAND], image: '/images/white/products/p-801438197.jpg', nm: 801438197, gallery: ['/images/white/products/p-801438197-2.jpg', '/images/white/products/p-801438197-3.jpg', '/images/white/products/p-801438197-b.jpg', '/images/white/products/p-801438197-d.jpg']},
  {key: 15, en: 'Draped Kimono Coat', ru: 'Пальто кимоно драповое', cat: 'outerwear', price: 34900, descEn: 'A draped wool kimono coat with a belt and a fluid fall. Architectural calm, cut to move.', descRu: 'Драповое пальто кимоно с поясом и текучим силуэтом. Архитектурное спокойствие, крой в движении.', compositionEn: 'Drape wool', compositionRu: 'Драп', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [CAMEL, {...CHARCOAL, image: '/images/white/products/p-795627344-charcoal.jpg', gallery: ['/images/white/products/p-795627344-charcoal-b.jpg', '/images/white/products/p-795627344-charcoal-d.jpg', '/images/white/products/p-795627344-charcoal-s.jpg', '/images/white/products/p-795627344-charcoal-m.jpg']}], image: '/images/white/products/p-795627344.jpg', nm: 795627344, gallery: ['/images/white/products/p-795627344-2.jpg', '/images/white/products/p-795627344-3.jpg', '/images/white/products/p-795627344-b.jpg', '/images/white/products/p-795627344-d.jpg']},
  {key: 16, en: 'Short Kimono Coat', ru: 'Пальто кимоно короткое', cat: 'outerwear', price: 34900, descEn: 'A cropped kimono coat with clean lines and a soft shoulder. The quiet finish to a look.', descRu: 'Укороченное пальто кимоно с чистыми линиями и мягким плечом. Тихое завершение образа.', compositionEn: 'Wool blend', compositionRu: 'Шерстяная смесь', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [SAND], image: '/images/white/products/p-795657866.jpg', nm: 795657866, gallery: ['/images/white/products/p-795657866-2.jpg', '/images/white/products/p-795657866-3.jpg', '/images/white/products/p-795657866-b.jpg', '/images/white/products/p-795657866-d.jpg']},
  {key: 17, en: 'Evening Dress', ru: 'Платье вечернее', cat: 'dresses', price: 1375, descEn: 'An occasion dress cut close and quiet. A clean neckline, a defined waist, made for evening.', descRu: 'Вечернее платье приталенного, сдержанного кроя. Чистая линия выреза, чёткая талия — для вечера.', compositionEn: 'Crepe', compositionRu: 'Креп', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [BLACK, {...BORDEAUX, image: '/images/white/products/p-192521903-bordeaux.jpg', gallery: ['/images/white/products/p-192521903-bordeaux-b.jpg', '/images/white/products/p-192521903-bordeaux-d.jpg', '/images/white/products/p-192521903-bordeaux-s.jpg', '/images/white/products/p-192521903-bordeaux-m.jpg']}], image: '/images/white/products/p-192521903.jpg', nm: 192521903, gallery: ['/images/white/products/p-192521903-2.jpg', '/images/white/products/p-192521903-d.jpg', '/images/white/products/p-192521903-b.jpg', '/images/white/products/p-192521903-s.jpg']},
  {key: 18, en: 'Lace Peplum Vest', ru: 'Жилет с баской и кружевом', cat: 'tailoring', price: 33400, descEn: 'A tailored peplum vest finished with lace. The sharpness of tailoring, softened at the edge.', descRu: 'Костюмный жилет с баской, завершённый кружевом. Острота тайлоринга, смягчённая по краю.', compositionEn: 'Wool blend with lace', compositionRu: 'Шерстяная смесь с кружевом', careEn: 'Dry clean only', careRu: 'Только химчистка', colors: [IVORY, {...BROWN, image: '/images/white/products/p-1224761706-brown.jpg', gallery: ['/images/white/products/p-1224761706-brown-b.jpg', '/images/white/products/p-1224761706-brown-d.jpg', '/images/white/products/p-1224761706-brown-s.jpg', '/images/white/products/p-1224761706-brown-m.jpg']}, {...GREY, image: '/images/white/products/p-1224761706-grey.jpg', gallery: ['/images/white/products/p-1224761706-grey-b.jpg', '/images/white/products/p-1224761706-grey-d.jpg', '/images/white/products/p-1224761706-grey-s.jpg', '/images/white/products/p-1224761706-grey-m.jpg']}, {...BLACK, image: '/images/white/products/p-1224761706-black.jpg', gallery: ['/images/white/products/p-1224761706-black-b.jpg', '/images/white/products/p-1224761706-black-d.jpg', '/images/white/products/p-1224761706-black-s.jpg', '/images/white/products/p-1224761706-black-m.jpg']}], image: '/images/white/products/p-1224761706.jpg', nm: 1224761706, gallery: ['/images/white/products/p-1224761706-b.jpg', '/images/white/products/p-1224761706-d.jpg', '/images/white/products/p-1224761706-s.jpg', '/images/white/products/p-1224761706-m.jpg']},
  {key: 19, en: 'School Ruffle Blouse', ru: 'Блузка школьная с воланами', cat: 'dresses', price: 3177, descEn: 'An oversized school blouse with soft ruffles — crisp cotton, a clean collar, easy volume. The uniform, made kind.', descRu: 'Школьная оверсайз-блузка с мягкими воланами — свежий хлопок, чистый воротник, лёгкий объём. Форма, ставшая доброй.', compositionEn: 'Cotton blend', compositionRu: 'Хлопковая смесь', careEn: 'Machine wash warm', careRu: 'Машинная стирка при 40°', colors: [BROWN, {...BLACK, image: '/images/white/products/p-1126294272-black.jpg', gallery: ['/images/white/products/p-1126294272-black-b.jpg', '/images/white/products/p-1126294272-black-d.jpg', '/images/white/products/p-1126294272-black-s.jpg', '/images/white/products/p-1126294272-black-m.jpg']}, {...IVORY, image: '/images/white/products/p-1126294272-ivory.jpg', gallery: ['/images/white/products/p-1126294272-ivory-b.jpg', '/images/white/products/p-1126294272-ivory-d.jpg', '/images/white/products/p-1126294272-ivory-s.jpg', '/images/white/products/p-1126294272-ivory-m.jpg']}], image: '/images/white/products/p-1126294272.jpg', nm: 1126294272, gallery: ['/images/white/products/p-1126294272-2.jpg', '/images/white/products/p-1126294272-d.jpg', '/images/white/products/p-1126294272-b.jpg', '/images/white/products/p-1126294272-s.jpg']},
];

// Editorial imagery — model-on-white shots generated for the White variant (the
// REINASLEO Soul), used for the hero, the atelier/lookbook block and as
// alternate PDP gallery views. Same-origin, so CSP img-src 'self' covers them.
export const WHITE_HERO_IMAGE = '/images/white/hero.jpg';
export const WHITE_ATELIER_IMAGE = '/images/white/editorial-1.jpg';
export const WHITE_EDITORIAL = ['/images/white/editorial-1.jpg', '/images/white/editorial-2.jpg', '/images/white/editorial-3.jpg'];

export function findWhiteProduct(key?: string | number | null): WhiteProduct | undefined {
  if (key == null) return undefined;
  const k = typeof key === 'string' ? Number.parseInt(key, 10) : key;
  if (Number.isNaN(k)) return undefined;
  return WHITE_PRODUCTS.find((p) => p.key === k);
}

export const WHITE_CATS: WhiteCat[] = ['dresses', 'outerwear', 'knitwear', 'tailoring', 'skirts'];

// Single source for the size run, shared by the PDP and the card Quick Add so
// they never drift. Demo sizing — real per-product runs arrive with the catalog.
export const WHITE_SIZES = ['XS', 'S', 'M', 'L', 'XL'] as const;
export type WhiteSize = (typeof WHITE_SIZES)[number];

// Validate a ?cat query value so the shop can be deep-linked/shared. Anything
// unrecognised collapses to 'all' (shared by server page + client showcase).
export function normalizeWhiteCat(value?: string | null): WhiteCat | 'all' {
  return value != null && (WHITE_CATS as string[]).includes(value) ? (value as WhiteCat) : 'all';
}

// Single source of category labels (en/ru), shared by the shop filter chips and
// the server-side <title>, so the two never drift. 'all' is contextual (chip
// reads "All", title reads "Shop"), so each caller supplies that label itself.
const WHITE_CAT_LABELS: Record<WhiteCat, [en: string, ru: string]> = {
  dresses: ['Dresses', 'Платья'],
  outerwear: ['Outerwear', 'Верхняя одежда'],
  knitwear: ['Knitwear', 'Трикотаж'],
  tailoring: ['Tailoring', 'Костюмы'],
  skirts: ['Skirts', 'Юбки'],
};
export function whiteCatLabel(cat: WhiteCat, locale: string): string {
  const [en, ru] = WHITE_CAT_LABELS[cat];
  return locale === 'ru' ? ru : en;
}

// Curated sets — looks assembled from the real catalogue, sold together or
// piece by piece. The image is the set's editorial mood; the items below it
// are the actual products (each with its own card and sizes).
export type WhiteSet = {
  key: string;
  en: string;
  ru: string;
  descEn: string;
  descRu: string;
  image: string;
  productKeys: number[];
};

export const WHITE_SETS: WhiteSet[] = [
  {key: 'office', en: 'The Office Edit', ru: 'В офис', descEn: 'Sharp tailoring that works the whole week: the peplum vest over draped trousers, the striped coat on top.', descRu: 'Строгий тайлоринг на всю неделю: жилет с баской поверх брюк алладинов, сверху — пальто в полоску.', image: '/images/white/editorial-2.jpg', productKeys: [3, 7, 13]},
  {key: 'summer', en: 'Summer in the City', ru: 'Лето в городе', descEn: 'Linen for the heat: the maxi suit, a lace shirt thrown over, the suede skort for lighter days.', descRu: 'Лён для жары: костюм с юбкой макси, поверх — рубашка с кружевом, на лёгкие дни — замшевая юбка-шорты.', image: '/images/white/atelier.jpg', productKeys: [1, 9, 10]},
  {key: 'evening', en: 'The Evening Out', ru: 'Вечерний выход', descEn: 'The corset with the satin balloon skirt, the fitted coat over the shoulders on the way home.', descRu: 'Корсет с атласной юбкой-баллон, по дороге домой — приталенное пальто на плечи.', image: '/images/white/editorial-1.jpg', productKeys: [6, 8, 2]},
  {key: 'everyday', en: 'Everyday Ease', ru: 'На каждый день', descEn: 'The bow sweatshirt with the balloon skirt, the short kimono coat when it cools down.', descRu: 'Свитшот с бантиками и юбка-баллон, когда холодает — короткое пальто кимоно.', image: '/images/white/editorial-3.jpg', productKeys: [4, 8, 16]},
];

export function findWhiteSet(key?: string | null): WhiteSet | undefined {
  return WHITE_SETS.find((s) => s.key === key);
}
